// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIUTqBauzbswawX_rue3kANdRfzjurUIM',
    appId: '1:210887905273:web:fe21929f02298b2a4e7728',
    messagingSenderId: '210887905273',
    projectId: 'store-app-f8e0c',
    authDomain: 'store-app-f8e0c.firebaseapp.com',
    storageBucket: 'store-app-f8e0c.firebasestorage.app',
    measurementId: 'G-NK1T8N7LTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA7k4txkkiqyP-GkgBag_W9dGHvAHLYJw',
    appId: '1:210887905273:android:6dc04ee45a0357aa4e7728',
    messagingSenderId: '210887905273',
    projectId: 'store-app-f8e0c',
    storageBucket: 'store-app-f8e0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTW0VgpWgygndKpx2btBHGtaq7dVBemtw',
    appId: '1:210887905273:ios:dbc6fdfef9d33e6a4e7728',
    messagingSenderId: '210887905273',
    projectId: 'store-app-f8e0c',
    storageBucket: 'store-app-f8e0c.firebasestorage.app',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTW0VgpWgygndKpx2btBHGtaq7dVBemtw',
    appId: '1:210887905273:ios:dbc6fdfef9d33e6a4e7728',
    messagingSenderId: '210887905273',
    projectId: 'store-app-f8e0c',
    storageBucket: 'store-app-f8e0c.firebasestorage.app',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIUTqBauzbswawX_rue3kANdRfzjurUIM',
    appId: '1:210887905273:web:ed671571315bc4854e7728',
    messagingSenderId: '210887905273',
    projectId: 'store-app-f8e0c',
    authDomain: 'store-app-f8e0c.firebaseapp.com',
    storageBucket: 'store-app-f8e0c.firebasestorage.app',
    measurementId: 'G-0YHB8N37BS',
  );
}
